menu:
  home: 首页
  archive: 归档
  tags: 标签
  category: 分类
  about: 关于
  RSS: RSS

pagination:
  prev: 上一页
  next: 下一页

posts:
  readmore: 阅读更多
  toc: 目录
  visits: 阅读次数

footer:
  powered: "由 %s 强力驱动"
  theme: 主题

counter:
  category:
    zero: "暂无分类"
    one: 共计一个分类
    other: "共计 %d 个分类"
  tagcloud:
    zero: "暂无标签"
    one: 共计1个标签
    other: "共计 %d 个标签"
